#!/usr/bin/env bash

set -euEo pipefail

# shellcheck source=scripts/commons
source "$( dirname "${BASH_SOURCE[0]}" )/scripts/commons"

# shellcheck source=scripts/logging
source "$( dirname "${BASH_SOURCE[0]}" )/scripts/logging"


declare ACTION_SHELL
ACTION_SHELL="shell"

declare ACTION_BUILD
ACTION_BUILD="build"

declare ACTION_UPLOAD_FILES
ACTION_UPLOAD_FILES="upload-files"

declare SSH_REMOTE_IP
SSH_REMOTE_IP="192.168.0.48"

declare ACTION_STREAM_CAMERA
ACTION_STREAM_CAMERA="stream-camera"


main()
{
    log_info "Welcome to Jean-Loup! "

    declare action
    action="${1:-}"
    test -z "${action}" && die "No action is provided! "
    shift 1

    case "${action}" in
        "${ACTION_SHELL}" )
                action_shell "${@}"
            ;;

        "${ACTION_BUILD}" )
                action_build "${@}"
            ;;

        "${ACTION_UPLOAD_FILES}" )
                action_upload_files "${@}"
            ;;

        "${ACTION_STREAM_CAMERA}" )
                action_stream_camera "${@}"
            ;;

        * )
                die "The ${action} action is unknonw! "
            ;;
    esac
}


declare CONNECTION_SERIAL
CONNECTION_SERIAL="serial"

declare CONNECTION_SSH
CONNECTION_SSH="ssh"

action_upload_files()
{
    declare ssh_remote_ip
    ssh_remote_ip="${SSH_REMOTE_IP}"

    while true; do
        case "${1:-}" in
            --ssh-remote-ip | -i )
                    ssh_remote_ip="${2:-}"
                    shift 2
                ;;

            --ssh-remote-ip=* )
                    ssh_remote_ip="${1#*=}"
                    shift 1
                ;;
            
            * )
                    break
                ;;
        esac
    done

    declare file_path
    for file_path in "${@}"; do
        scp \
            -o StrictHostKeychecking="no" \
            -o UserKnownHostsFile="/dev/null" \
                "${file_path}" "alarm@${ssh_remote_ip}:~/"
    done
}


action_shell()
{
    log_info "Let's shell! "
    declare connection
    connection="${CONNECTION_SERIAL}"

    declare serial_device
    serial_device="/dev/ttyUSB0"

    declare ssh_remote_ip
    ssh_remote_ip="${SSH_REMOTE_IP}"

    while true; do
        case "${1:-}" in
            --connection | -c )
                    connection="${2:-}"
                    shift 2
                ;;

            --connection=* )
                    connection="${1#*=}"
                    shift 1
                ;;

            --serial-device | -d )
                    serial_device="${2:-}"
                    shift 2
                ;;
            
            --serial-device=* )
                    serial_device="${1#*=}"
                    shift 1
                ;;

            --ssh-remote-ip | -i )
                    ssh_remote_ip="${2:-}"
                    shift 2
                ;;

            --ssh-remote-ip=* )
                    ssh_remote_ip="${1#*=}"
                    shift 1
                ;;
            
            * )
                    break
                ;;
        esac
    done

    case "${connection}" in
        "${CONNECTION_SERIAL}" )
                sudo -E minicom -b 115200 -D "${serial_device}"
            ;;

        "${CONNECTION_SSH}" )
                ssh \
                    -o StrictHostKeychecking="no" \
                    -o UserKnownHostsFile="/dev/null" \
                        "alarm@${ssh_remote_ip}"
            ;;

        *)
                die "The ${connection} connection is not supported! "
            ;;
    esac
}


action_stream_camera()
{
    invoke_ssh "alarm@${SSH_REMOTE_IP}" "sudo rpicam-vid --nopreview --width 200 --height 100 --timeout 0 --inline --output -" | ffplay -hide_banner -loglevel error -
}


action_build()
{
    log_info "Let's build! "
}

invoke_ssh()
{
    ssh \
        -o StrictHostKeychecking="no" \
        -o UserKnownHostsFile="/dev/null" \
            "${@}"
}


main "${@}"